### ISSUE TITLE
Are all the calls to `recursively` really needed?

### ISSUE THREAD

**Issue by jvoigtlaender** [drenninghoff/bachelorthesis#10]
In fact, I think only the one call in `term`, calling itself directly without any guarding by a lambda-abstraction, is where `recursively` is needed. Everywhere else it should be superfluous.

**Comment by drenninghoff** [comment]
I found an even better solution. I removed all `recursively` calls and replaced them (where needed) with lambda expressions. That way I can drop the custom Parsing library.
