### ISSUE TITLE
Add example Prolog programs

### ISSUE THREAD

**Issue by jvoigtlaender** [drenninghoff/bachelorthesis#11]
By default, all the ones from the lecture slides that do not use features not implemented here.

**Comment by jvoigtlaender** [comment]
Adding them as files in addition or instead of as menu items.

**Comment by drenninghoff** [comment]
What is preferred? Seperate files or menu items?

**Comment by jvoigtlaender** [comment]
I'd say separate files.

**Comment by jvoigtlaender** [comment]
No examples using lists at all? I proposed "all the [examples] from the lecture slides that do not use features not implemented here". Certainly there are more in that category than the three example files you now have.

**Comment by drenninghoff** [comment]
Sorry, seems like I missed the

**Comment by drenninghoff** [comment]
Sorry, seems like I missed the quicksort example.
