### ISSUE TITLE
Handling/non-handling of anonymous variables.

### ISSUE THREAD

**Issue by jvoigtlaender** [drenninghoff/bachelorthesis#13]
The parser now again accepts "_" as a variable, but the evaluator doesn't give it the special treatment that it would receive in Prolog.

For the record:

 *If* "_" is accepted as a variable, then the following program:
```prolog
q(s(a),s(b)).
p(X) :- q(X,X).
```
*should* allow `q(_,_)` to be derived, but *not* `p(s(_))`.

**Comment by drenninghoff** [comment]
"_" is not accepted anymore.
